{EQEmu PR 2635} Improve Quest Error Handling As a server operator, I want to be able to be aware when errors happen reliably in my scripts in real time and not have to go through potentially many manual steps to find out. Error feedback should be immediate and simple.
**Solution**

* Add Logging category `QuestErrors` that is enabled by default for **console** and **gmsay**. This ensures that errors are always bubbled to the surface immediately and doesn't require things to be turned on to be aware of them.
* Perl syntax checking is now occurring via process invocation since the eval API is not properly picking syntax issues up

**Examples**

**Perl**

```
[Zone] [QuestErrors] Error Compiling NPC Quest File [quests/qrg/zone_controller.pl] NPC ID [10] Error [Missing right curly or square bracket at quests/qrg/zone_controller.pl line 24, at end of line
syntax error at quests/qrg/zone_controller.pl line 24, at EOF
quests/qrg/zone_controller.pl had compilation errors.]
```

![image](https://user-images.githubusercontent.com/3319450/206991959-0872bb30-0f33-4374-92c8-139d19dcd3ab.png)

**Lua**

```
[Zone] [QuestErrors] quests/qrg/Vesteri_Nomanoi.lua:14: '=' expected near 'if'
```
![image](https://user-images.githubusercontent.com/3319450/206991927-ce9bc018-2c7b-4621-9aaa-fe2cdb04107c.png)

**#questerrors**

#questerrors will now report Perl syntax issues reliably as well

![image](https://user-images.githubusercontent.com/3319450/206994257-4d174ee3-c949-41a7-9efa-c82e470c6abb.png)